#!/bin/sh

ulimit -c unlimited
ulimit -n 8192
./magic_Linux32 /r ./ /e /ccs/pack_data/lib_ccs32.pak/ccs/start_ccs.o /b /ccs/pack_data/lib_ccs32.pak -m ccs/ccsmem.cfg /D _RELEASE /D TRADITIONAL --max-process 128 --enable-socket-daemon 0
